# -----------------------------------------------------------------------------
# mbconfig.py
#
# This is Python module for ModbusTools server configuration.
# It is autogenerated and intended to be converted into a usable Python module
# containing configuration parameters and logic for the Modbus server.
# -----------------------------------------------------------------------------

# Major part of mbtools version
MBTOOLS_VERSION_MAJOR = 0

# Minor part of mbtools version
MBTOOLS_VERSION_MINOR = 4

# Patch part of mbtools version
MBTOOLS_VERSION_PATCH = 4
