# -----------------------------------------------------------------------------
# mbconfig.py
#
# DO NOT EDIT THIS FILE! It is autogenerated.
#
# This is Python module for ModbusTools server configuration.
# It is intended to be converted into a usable Python module
# containing configuration parameters and logic for the Modbus server.
# -----------------------------------------------------------------------------

# Major part of mbtools version
MBTOOLS_VERSION_MAJOR = 0

# Minor part of mbtools version
MBTOOLS_VERSION_MINOR = 5

# Patch part of mbtools version
MBTOOLS_VERSION_PATCH = 0

# Integer representation of mbtools version
MBTOOLS_VERSION_INT = (0 << 16) | (5 << 8) | 0

# String representation of mbtools version
MBTOOLS_VERSION_STR = "0.5.0"
